### ISSUE TITLE
Setup app to use Bootstrap and SCSS for styling

### ISSUE THREAD

**Issue by prestoncabe** [CircleOfHope/circlemusic#18]

**Comment by benirose** [comment]
Glad you opened this, I've been researching it all weekend. I'm experimenting with using the `bootstrap-sass` module and will try to post results once I finish. It feels a little clunky to me, so I want to make sure it's working for us before we move forward.

**Comment by benirose** [comment]
Just wanted to document my progress. I'm using [SASS Middleware](https://github.com/sass/node-sass-middleware) similar to how I was doing it with LESS in the past. This line just tells us when requesting anything at `/css`, to use the middleware, which will check to see if there's a SASS file with the same name to compile (also checking update times to see if it needs a recompile due to changes).

``` javascript
app.use('/css', sassMiddleware({
    src: path.join(__dirname, 'public/css'),
    response: false
}));
```

**Quick question**: I'm used to putting LESS/SASS files in the same spot in the `public` folder, however you can specify a different `src` and `dest` location, so we could have our SASS in a different location than `public/css` and have it compile to that location.

The hard part isn't getting the middleware to compile the SASS when needed, but hooking Bootstrap to compile. Bootstrap requires a `postCSS` processor called `Autoprefix`, so hooking that in adds extra code in app.js. I'm testing that now.

As far as actually including via NPM, there are two paths. One is including bootstrap via `import` in our main `styles.scss` so that it gets amalgamated into a single CSS file upon compilation. This would mean any time we make changes to our own CSS, it will recompile all of Bootstrap SASS. I'll have to test timing on this to see if it's a big lift or not.

Rather than having our layout include a single CSS file (via link tags) we could include one just for the bootstrap and one for custom site styles. This way the bootstrap SASS only compiles when we make changes to the variables that affect it (or any theme we're using) vs site specific SASS. I'm not 100% sure what site specific SASS will be used for that, or even how much changes we'll be making to SASS, so it may end up being fairly irrelevant.

Looking for input on this, if any of it even made sense. We can always change it down the line, so assuming Bootstrap build doesn't add a horrendous amount of time to server start/recompile I will start with that path.

**Comment by benirose** [comment]
So I just spent way too many hours butting heads with the `autoprefix` PostCSS plugin wondering why on earth it wasn't auto-prefixing my CSS, as Bootstrap requires this. Many `console.log`s later I eventually found out it was! It had been sending auto-prefixed CSS to my browser every time, but I was checking my generated CSS expecting the changes to be there!

I had found a simpler [autoprefix middleware module](https://www.npmjs.com/package/express-autoprefixer) which would be a bit more light weight than the [postCSS middleware module](https://github.com/jedmao/postcss-middleware) that basically is wrapping Gulp as a middleware, which then takes the [autoprefix postCSS plugin](https://github.com/postcss/autoprefixer) as a plugin option. The later felt super bulky and hacky to get autoprefixing (this is clearly supposed to be part of your Gulp/Grunt/Webpack/whatever process, and not something that happens during a server start-up/request...but I haven't bought into the "build tool are awesome" hype when you can build processes run as needed without having to install extra global npm modules and remember to run/watch things).

Anyways, using either`express-autoprefixer` or `postcss-middleware` with `autoprefix` directly seem to both be auto-prefixing the CSS on every request and responding with the output rather than writing to the file if it's been changed (like `SASS middleware` is doing), which seems a bit much to me. It looks like `express-autoprefixer` doesn't allow any other way, so I have to dig into `postcss-middleware` to see if I can get it to write the auto-prefixed CSS back to the file rather than directly to the response and check for modifications before doing so.

Alternately, we could use build tools.

**Comment by prestoncabe** [comment]
I'm not going to be much help on this except to affirm the approach of just making it work now and then we can optimize later as needed.

To the extent I've done styling things at all, I'm used to letting rails and various gems hold my hand, sticking to tutorials and copying from example projects when needed.

**Comment by benirose** [comment]
I've spent way too long on this. It seems like I would have to write my own middleware if I wanted a version of `autoprefixer` that only runs on modified files and writes to the file instead of just responding. Perhaps some day I can do that, but for now we can live with the CSS getting autoprefixed every time they are requested. Going to test with actual bootstrap SASS now to see what that might mean for response time.

**Comment by prestoncabe** [comment]
Sounds good
