### ISSUE TITLE
Developers can import all song data from the legacy database

### ISSUE THREAD

**Issue by prestoncabe** [CircleOfHope/circlemusic#5]
We'll need an easily repeatable method for importing all data from the legacy database so we can:
- test using actual data
- quickly do the "final" import when we make the switch to using the new app

**Comment by benirose** [comment]
Spent some time on this this morning. Trying not to get bogged down in details like loading an external config for mysql and mongo connections and how that should be done. Still proved to be harder than I was expecting because of translating the normalized data into denormalized documents. First I tried to get a single query to pull everything, using `GROUP_CONCAT` in MySQL, but I'm worried it might get truncated, so I'll probably end up just looping over songs to pull in tags and attachments. Doesn't need to be performant since it will run pretty rarely.

**Comment by benirose** [comment]
I've gotten the import script working for songs (including tags and links). It currently takes the name of the MySQL database as the only argument but I quickly realized it needs host/user/pass arguments as well. 

Should I:
a) add argument flags, ex: `bin/import --database=musictable_php --user=root --password=root`
b) have it load in from a config file that does not get committed so we can specify to machine

Obviously typing flags every time is a pain, but it's not meant to be run often, and adding a config situation is a bit more complex. Also `mysql` is only a dev dependency, and not required to run the server, so adding files across the code base to support a dev process that only happens once in a while feels cluttery to me (although it does happen for other build related things).

**Comment by benirose** [comment]
Also I'm not crazy about including a mysql db password on the command line, but it will likely only ever be run on our machines.
